# Generated by Django 2.0.6 on 2020-02-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200201_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(max_length=30, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '题目', 'verbose_name_plural': '题目'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_updated_time',
        ),
        migrations.AddField(
            model_name='article',
            name='choice_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType', verbose_name='选择类别'),
        ),
    ]
