# Generated by Django 2.0.6 on 2020-02-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200202_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletype',
            old_name='article_type',
            new_name='type_name',
        ),
    ]
