# Generated by Django 2.0.6 on 2020-02-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200203_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='choice_type',
            new_name='article_type',
        ),
    ]
