# Generated by Django 2.0.6 on 2020-01-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_class',
            field=models.CharField(choices=[('周五 18:00-20:00', 'A班'), ('周六 13:00-14:30', 'B班')], default=((1, 'A'), (2, 'B')), max_length=50, verbose_name='班级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_counts',
            field=models.IntegerField(default=15, verbose_name='总课时'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('One', 1), ('Two', 2), ('Three', 3), ('Four', 4), ('Five', 5), ('Six', 6)], default=2, max_length=50, verbose_name='阶段'),
            preserve_default=False,
        ),
    ]
