# Generated by Django 2.0.6 on 2020-01-31 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200131_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=50, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('tel', models.IntegerField(verbose_name='联系电话')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='course_class',
            field=models.CharField(choices=[('Friday 18:00-20:00', '周五 18:00-20:00'), ('Saturday 13:00-14:30', '周六 13:00-14:30'), ('Saturday 18:30-20:00', '周六 18:30-20:00'), ('Sunday 13:00-14:30', '周日 13:00-14:30'), ('Sunday 15:15-16:45', '周日 15:15-16:45'), ('Sunday 18:00-19:30', '周日 18:00-19:30')], max_length=50, verbose_name='上课时间'),
        ),
        migrations.AddField(
            model_name='students',
            name='course_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Course', verbose_name='课程'),
        ),
    ]
