# Generated by Django 2.0.6 on 2020-01-31 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200131_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='教师姓名')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='course_class',
            field=models.CharField(choices=[('周五 18:00-20:00', '周五 18:00-20:00'), ('周六 13:00-14:30', '周六 13:00-14:30'), ('周六 18:30-20:00', '周六 18:30-20:00'), ('周日 13:00-14:30', '周日 13:00-14:30'), ('周日 15:15-16:45', '周日 15:15-16:45'), ('周日 18:00-19:30', '周日 18:00-19:30')], max_length=50, verbose_name='上课时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('一阶', 1), ('二阶', 2), ('三阶', 3), ('四阶', 4), ('五阶', 5), ('六阶', 6)], max_length=50, verbose_name='阶段'),
        ),
        migrations.AddField(
            model_name='course',
            name='who_teach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Teachers', verbose_name='教师'),
        ),
    ]
